# Curriculum config to abbreviate all blocks for GitHub workflow
num learn blocks: 1  # MiniGridDispersed will do all learning in one block
learn:
  default length: 5  # All task variants in learn blocks will run 5 episodes
eval:
  default length: 5  # All task variants in eval blocks will run 5 episodes
