# Copyright © 2021-2022 The Johns Hopkins University Applied Physics Laboratory LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# A YAML config file formatted for M21 minigrid curriculums

# This config is not meant to be used; instead it demonstrates
#   the expected fields and formatting rules

learn:  # Only learning block lengths are configurable. Use this header for all limits

  # Task variants are limited by an integer length counted using the unit "episodes" or "steps"

  default length: 12345  # Task variants without lengths given here use this length (default: 1000)
  default unit: steps  # Task variants without units given here use this unit (default: episodes)

  # Limits can be specified as an integer, in which case the default unit is used
  SimpleCrossingS9N1: 1111

  # Or limits can be specified as a dict, in which case the values of "length" and "unit" will be used if present
  SimpleCrossingS9N2:
    length: 2222  # Length still must be an integer
    unit: episodes  # And unit must be "episodes" or "steps"
  SimpleCrossingS9N3:
    unit: episodes
    length: 3333
  DistShiftR2:
    length: 4444
  DistShiftR5:
    unit: steps

  # Limits can be specified for a task variant, or for a whole task, in which case all variants are affected
  DistShiftR3: 6666
  DynObstacles: 7777  # DynObstaclesS6N1, DynObstaclesS8N2, and DynObstaclesS10N3 will use this limit

  # If limits are specified for a task and also a specific variant of that task, the variant values are used
  CustomFetch: 1234  # CustomFetchS5T1N2 and CustomFetchS8T1N2 will use this limit
  CustomFetchS10T2N4: 5678  # But CustomFetchS10T2N4 is set separately

# Curriculums can define their own config interpreters. MiniGridDispersed accepts one additional field:
num learn blocks: 5  # MiniGridDispersed splits learning into this many blocks (default 3)
# Note that the specified limits above are also divided into this many blocks, so that the specified
#   limit is the total reached over all learning blocks

# For verification, here are the limits that each task variant would use under this config
#  SimpleCrossingS9N1: 1111 steps
#  SimpleCrossingS9N2: 2222 episodes
#  SimpleCrossingS9N3: 3333 episodes
#  DistShiftR2: 4444 steps
#  DistShiftR5: 12345 steps
#  DistShiftR3: 6666 steps
#  DynObstaclesS6N1: 7777 steps
#  DynObstaclesS8N2: 7777 steps
#  DynObstaclesS10N3: 777 steps
#  CustomFetchS5T1N2: 1234 steps
#  CustomFetchS8T1N2: 1234 steps
#  CustomFetchS10T2N4: 5678 steps
#  CustomUnlockS5: 12345 steps
#  CustomUnlockS7: 12345 steps
#  CustomUnlockS9: 12345 steps
#  DoorKeyS5: 12345 steps
#  DoorKeyS6: 12345 steps
#  DoorKeyS7: 12345 steps
