# A YAML config file formatted for M21 minigrid curriculums

# Here, each task in the M21 curriculum is given a different limit
#   using the default unit, which is episodes

learn:
  SimpleCrossingS9N1: 1111
  SimpleCrossingS9N2: 2222
  SimpleCrossingS9N3: 3333
  DistShiftR2: 4444
  DistShiftR5: 5555
  DistShiftR3: 6666
  DynObstaclesS6N1: 7777
  DynObstaclesS8N2: 8888
  DynObstaclesS10N3: 9999
  CustomFetchS5T1N2: 1010
  CustomFetchS8T1N2: 1111
  CustomFetchS16T2N4: 1212
  CustomUnlockS5: 1313
  CustomUnlockS7: 1414
  CustomUnlockS9: 1515
  DoorKeyS5: 1616
  DoorKeyS6: 1717
  DoorKeyS8: 1818
