name: Docs Check
on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tella
      uses: actions/checkout@v2
      with:
        path: tella
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ./tella[minigrid]
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: ./tella/docs/
