name: Docs Check
on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: docs/
        build-command: "sphinx-build -b html . _build -W"
